# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/preprocess_control.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrepCtrlWidget(object):
    def setupUi(self, PrepCtrlWidget):
        PrepCtrlWidget.setObjectName("PrepCtrlWidget")
        PrepCtrlWidget.setWindowModality(QtCore.Qt.NonModal)
        PrepCtrlWidget.resize(375, 307)
        self.verticalLayout = QtWidgets.QVBoxLayout(PrepCtrlWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_params = QtWidgets.QFormLayout()
        self.layout_params.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_params.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.layout_params.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.layout_params.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.layout_params.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.layout_params.setContentsMargins(0, -1, -1, -1)
        self.layout_params.setObjectName("layout_params")
        self.label_display_source = QtWidgets.QLabel(PrepCtrlWidget)
        self.label_display_source.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_display_source.setFont(font)
        self.label_display_source.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_display_source.setObjectName("label_display_source")
        self.layout_params.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_display_source)
        self.combo_source = QtWidgets.QComboBox(PrepCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_source.sizePolicy().hasHeightForWidth())
        self.combo_source.setSizePolicy(sizePolicy)
        self.combo_source.setMinimumSize(QtCore.QSize(180, 0))
        self.combo_source.setObjectName("combo_source")
        self.combo_source.addItem("")
        self.combo_source.addItem("")
        self.combo_source.addItem("")
        self.combo_source.addItem("")
        self.combo_source.addItem("")
        self.layout_params.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_source)
        self.label_total_pixels = QtWidgets.QLabel(PrepCtrlWidget)
        self.label_total_pixels.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_total_pixels.setFont(font)
        self.label_total_pixels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_total_pixels.setObjectName("label_total_pixels")
        self.layout_params.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_total_pixels)
        self.linedit_total_pixels = QtWidgets.QLineEdit(PrepCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linedit_total_pixels.sizePolicy().hasHeightForWidth())
        self.linedit_total_pixels.setSizePolicy(sizePolicy)
        self.linedit_total_pixels.setMinimumSize(QtCore.QSize(180, 0))
        self.linedit_total_pixels.setObjectName("linedit_total_pixels")
        self.layout_params.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.linedit_total_pixels)
        self.label_bilateral_params = QtWidgets.QLabel(PrepCtrlWidget)
        self.label_bilateral_params.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_bilateral_params.setFont(font)
        self.label_bilateral_params.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_bilateral_params.setObjectName("label_bilateral_params")
        self.layout_params.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_bilateral_params)
        self.layout_bilateral_param1 = QtWidgets.QHBoxLayout()
        self.layout_bilateral_param1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_bilateral_param1.setContentsMargins(-1, -1, 0, -1)
        self.layout_bilateral_param1.setSpacing(7)
        self.layout_bilateral_param1.setObjectName("layout_bilateral_param1")
        self.label_bilateral_arg1 = QtWidgets.QLabel(PrepCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bilateral_arg1.sizePolicy().hasHeightForWidth())
        self.label_bilateral_arg1.setSizePolicy(sizePolicy)
        self.label_bilateral_arg1.setMinimumSize(QtCore.QSize(40, 0))
        self.label_bilateral_arg1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_bilateral_arg1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_bilateral_arg1.setFont(font)
        self.label_bilateral_arg1.setObjectName("label_bilateral_arg1")
        self.layout_bilateral_param1.addWidget(self.label_bilateral_arg1)
        self.spinbox_bilateral_arg1 = QtWidgets.QSpinBox(PrepCtrlWidget)
        self.spinbox_bilateral_arg1.setMinimumSize(QtCore.QSize(132, 0))
        self.spinbox_bilateral_arg1.setMaximumSize(QtCore.QSize(132, 16777215))
        self.spinbox_bilateral_arg1.setMinimum(-1)
        self.spinbox_bilateral_arg1.setMaximum(999)
        self.spinbox_bilateral_arg1.setSingleStep(1)
        self.spinbox_bilateral_arg1.setProperty("value", 21)
        self.spinbox_bilateral_arg1.setObjectName("spinbox_bilateral_arg1")
        self.layout_bilateral_param1.addWidget(self.spinbox_bilateral_arg1)
        self.layout_bilateral_param1.setStretch(0, 1)
        self.layout_bilateral_param1.setStretch(1, 1)
        self.layout_params.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.layout_bilateral_param1)
        self.layout_bilateral_param2 = QtWidgets.QHBoxLayout()
        self.layout_bilateral_param2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_bilateral_param2.setContentsMargins(-1, -1, 0, -1)
        self.layout_bilateral_param2.setObjectName("layout_bilateral_param2")
        self.label_bilateral_arg2 = QtWidgets.QLabel(PrepCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bilateral_arg2.sizePolicy().hasHeightForWidth())
        self.label_bilateral_arg2.setSizePolicy(sizePolicy)
        self.label_bilateral_arg2.setMinimumSize(QtCore.QSize(40, 0))
        self.label_bilateral_arg2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_bilateral_arg2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_bilateral_arg2.setFont(font)
        self.label_bilateral_arg2.setObjectName("label_bilateral_arg2")
        self.layout_bilateral_param2.addWidget(self.label_bilateral_arg2)
        self.spinbox_bilateral_arg2 = QtWidgets.QSpinBox(PrepCtrlWidget)
        self.spinbox_bilateral_arg2.setMinimumSize(QtCore.QSize(132, 0))
        self.spinbox_bilateral_arg2.setMaximumSize(QtCore.QSize(132, 16777215))
        self.spinbox_bilateral_arg2.setMinimum(-1)
        self.spinbox_bilateral_arg2.setMaximum(999)
        self.spinbox_bilateral_arg2.setProperty("value", 21)
        self.spinbox_bilateral_arg2.setObjectName("spinbox_bilateral_arg2")
        self.layout_bilateral_param2.addWidget(self.spinbox_bilateral_arg2)
        self.layout_params.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.layout_bilateral_param2)
        self.label_gaussian_size = QtWidgets.QLabel(PrepCtrlWidget)
        self.label_gaussian_size.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_gaussian_size.setFont(font)
        self.label_gaussian_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_gaussian_size.setObjectName("label_gaussian_size")
        self.layout_params.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_gaussian_size)
        self.label_offset = QtWidgets.QLabel(PrepCtrlWidget)
        self.label_offset.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_offset.setFont(font)
        self.label_offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_offset.setObjectName("label_offset")
        self.layout_params.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_offset)
        self.checkbox_show_verbose = QtWidgets.QCheckBox(PrepCtrlWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_show_verbose.setFont(font)
        self.checkbox_show_verbose.setChecked(False)
        self.checkbox_show_verbose.setObjectName("checkbox_show_verbose")
        self.layout_params.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.checkbox_show_verbose)
        self.layout_bilateral_param3 = QtWidgets.QHBoxLayout()
        self.layout_bilateral_param3.setContentsMargins(-1, -1, 0, -1)
        self.layout_bilateral_param3.setObjectName("layout_bilateral_param3")
        self.label_bilateral_arg3 = QtWidgets.QLabel(PrepCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bilateral_arg3.sizePolicy().hasHeightForWidth())
        self.label_bilateral_arg3.setSizePolicy(sizePolicy)
        self.label_bilateral_arg3.setMinimumSize(QtCore.QSize(40, 0))
        self.label_bilateral_arg3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_bilateral_arg3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_bilateral_arg3.setFont(font)
        self.label_bilateral_arg3.setObjectName("label_bilateral_arg3")
        self.layout_bilateral_param3.addWidget(self.label_bilateral_arg3)
        self.spinbox_bilateral_arg3 = QtWidgets.QSpinBox(PrepCtrlWidget)
        self.spinbox_bilateral_arg3.setMinimumSize(QtCore.QSize(132, 0))
        self.spinbox_bilateral_arg3.setMaximumSize(QtCore.QSize(132, 16777215))
        self.spinbox_bilateral_arg3.setMinimum(-1)
        self.spinbox_bilateral_arg3.setMaximum(999)
        self.spinbox_bilateral_arg3.setProperty("value", 21)
        self.spinbox_bilateral_arg3.setObjectName("spinbox_bilateral_arg3")
        self.layout_bilateral_param3.addWidget(self.spinbox_bilateral_arg3)
        self.layout_params.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.layout_bilateral_param3)
        self.spinbox_gaussian_size = QtWidgets.QSpinBox(PrepCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_gaussian_size.sizePolicy().hasHeightForWidth())
        self.spinbox_gaussian_size.setSizePolicy(sizePolicy)
        self.spinbox_gaussian_size.setMinimumSize(QtCore.QSize(180, 0))
        self.spinbox_gaussian_size.setMinimum(3)
        self.spinbox_gaussian_size.setMaximum(1000)
        self.spinbox_gaussian_size.setProperty("value", 255)
        self.spinbox_gaussian_size.setDisplayIntegerBase(10)
        self.spinbox_gaussian_size.setObjectName("spinbox_gaussian_size")
        self.layout_params.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinbox_gaussian_size)
        self.dspinbox_offset = QtWidgets.QDoubleSpinBox(PrepCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dspinbox_offset.sizePolicy().hasHeightForWidth())
        self.dspinbox_offset.setSizePolicy(sizePolicy)
        self.dspinbox_offset.setMinimumSize(QtCore.QSize(180, 0))
        self.dspinbox_offset.setMaximum(0.99)
        self.dspinbox_offset.setSingleStep(0.01)
        self.dspinbox_offset.setProperty("value", 0.15)
        self.dspinbox_offset.setObjectName("dspinbox_offset")
        self.layout_params.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dspinbox_offset)
        self.verticalLayout.addLayout(self.layout_params)
        self.btn_ok = QtWidgets.QPushButton(PrepCtrlWidget)
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout.addWidget(self.btn_ok)

        self.retranslateUi(PrepCtrlWidget)
        QtCore.QMetaObject.connectSlotsByName(PrepCtrlWidget)

    def retranslateUi(self, PrepCtrlWidget):
        _translate = QtCore.QCoreApplication.translate
        PrepCtrlWidget.setWindowTitle(_translate("PrepCtrlWidget", "Preprocess Control Panel"))
        self.label_display_source.setText(_translate("PrepCtrlWidget", "Display Source :"))
        self.combo_source.setItemText(0, _translate("PrepCtrlWidget", "Color Image (RGB)"))
        self.combo_source.setItemText(1, _translate("PrepCtrlWidget", "Gray"))
        self.combo_source.setItemText(2, _translate("PrepCtrlWidget", "Blue Channel"))
        self.combo_source.setItemText(3, _translate("PrepCtrlWidget", "Red Channel"))
        self.combo_source.setItemText(4, _translate("PrepCtrlWidget", "Green Channel"))
        self.label_total_pixels.setText(_translate("PrepCtrlWidget", "Total Pixels :"))
        self.linedit_total_pixels.setText(_translate("PrepCtrlWidget", "400000"))
        self.label_bilateral_params.setText(_translate("PrepCtrlWidget", "Bilateral Params:"))
        self.label_bilateral_arg1.setText(_translate("PrepCtrlWidget", "arg1:"))
        self.label_bilateral_arg2.setText(_translate("PrepCtrlWidget", "arg2:"))
        self.label_gaussian_size.setText(_translate("PrepCtrlWidget", "Gaussian Size:"))
        self.label_offset.setText(_translate("PrepCtrlWidget", "Offset:"))
        self.checkbox_show_verbose.setText(_translate("PrepCtrlWidget", "Show Verbose"))
        self.label_bilateral_arg3.setText(_translate("PrepCtrlWidget", "arg3:"))
        self.btn_ok.setText(_translate("PrepCtrlWidget", "OK"))
